// js/react/src/BlitTerminal.tsx
import { useEffect, useImperativeHandle, useRef } from "react";
import type { Ref } from "react";
import type { ConnectionStatus } from "@blit-sh/core";
import type { Terminal } from "@blit-sh/browser";
import { BlitTerminalSurface } from "@blit-sh/core";
import type { BlitTerminalProps } from "./types";
import { useBlitContext, useRequiredBlitWorkspace } from "./BlitContext";
import { useBlitConnection } from "./hooks/useBlitConnection";
import { useBlitSession } from "./hooks/useBlitSession";

// ---------------------------------------------------------------------------
// Public handle exposed via ref
// ---------------------------------------------------------------------------

export interface BlitTerminalHandle {
  /** The underlying WASM Terminal instance, if initialised. */
  terminal: Terminal | null;
  /** Current grid dimensions. */
  rows: number;
  cols: number;
  /** Current connection status. */
  status: ConnectionStatus;
  /** Focus the input sink so the terminal can receive keyboard events. */
  focus(): void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * BlitTerminal renders a blit terminal inside a WebGL canvas.
 *
 * This is a thin wrapper over `BlitTerminalSurface` from `@blit-sh/core`.
 * It renders a container `<div>`, attaches the surface to it on mount,
 * and forwards prop changes to the surface's setters.
 */
export function BlitTerminal({
  ref,
  ...props
}: BlitTerminalProps & { ref?: Ref<BlitTerminalHandle> }) {
  const ctx = useBlitContext();
  const workspace = useRequiredBlitWorkspace();
  const session = useBlitSession(props.sessionId);
  const connection = useBlitConnection(session?.connectionId);
  const blitConn = session
    ? workspace.getConnection(session.connectionId)
    : null;

  const {
    sessionId,
    fontFamily = ctx.fontFamily,
    fontSize = ctx.fontSize,
    className,
    style,
    palette = ctx.palette,
    readOnly,
    showCursor,
    onRender,
    scrollbarColor,
    scrollbarWidth,
    advanceRatio = ctx.advanceRatio,
  } = props;

  const containerRef = useRef<HTMLDivElement>(null);
  const surfaceRef = useRef<BlitTerminalSurface | null>(null);

  // Create the surface once on mount.
  useEffect(() => {
    const surface = new BlitTerminalSurface({
      sessionId,
      fontFamily,
      fontSize,
      palette,
      readOnly,
      showCursor,
      onRender,
      scrollbarColor,
      scrollbarWidth,
      advanceRatio,
    });
    surfaceRef.current = surface;

    return () => {
      surface.dispose();
      surfaceRef.current = null;
    };
    // Only create/destroy on mount/unmount. Props are forwarded via setters.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Attach/detach to the container div.
  useEffect(() => {
    const surface = surfaceRef.current;
    const container = containerRef.current;
    if (!surface || !container) return;
    surface.attach(container);
    return () => surface.detach();
  }, []);

  // Forward workspace + connection.
  useEffect(() => {
    surfaceRef.current?.setWorkspace(workspace);
  }, [workspace]);

  useEffect(() => {
    surfaceRef.current?.setConnection(blitConn);
  }, [blitConn]);

  // Forward all prop changes.
  useEffect(() => {
    surfaceRef.current?.setSessionId(sessionId);
  }, [sessionId]);

  useEffect(() => {
    surfaceRef.current?.setPalette(palette);
  }, [palette]);

  useEffect(() => {
    surfaceRef.current?.setFontFamily(fontFamily);
  }, [fontFamily]);

  useEffect(() => {
    surfaceRef.current?.setFontSize(fontSize);
  }, [fontSize]);

  useEffect(() => {
    surfaceRef.current?.setShowCursor(showCursor);
  }, [showCursor]);

  useEffect(() => {
    surfaceRef.current?.setOnRender(onRender);
  }, [onRender]);

  useEffect(() => {
    surfaceRef.current?.setAdvanceRatio(advanceRatio);
  }, [advanceRatio]);

  useEffect(() => {
    surfaceRef.current?.setReadOnly(readOnly);
  }, [readOnly]);

  // Re-send dimensions when connection becomes ready.
  const status: ConnectionStatus = connection?.status ?? "disconnected";
  useEffect(() => {
    if (status === "connected" && sessionId !== null && !readOnly) {
      surfaceRef.current?.resendSize();
    }
  }, [status, sessionId, readOnly]);

  // Imperative handle.
  useImperativeHandle(
    ref,
    () => ({
      get terminal() {
        return surfaceRef.current?.currentTerminal ?? null;
      },
      get rows() {
        return surfaceRef.current?.rows ?? 24;
      },
      get cols() {
        return surfaceRef.current?.cols ?? 80;
      },
      status,
      focus() {
        surfaceRef.current?.focus();
      },
    }),
    [status],
  );

  return (
    <div
      ref={containerRef}
      className={className}
      style={{
        position: "relative",
        overflow: "hidden",
        ...style,
      }}
    />
  );
}

// js/solid/src/BlitTerminal.tsx
import { onMount, onCleanup, createEffect, type JSX } from "solid-js";
import { BlitTerminalSurface } from "@blit-sh/core";
import type { SessionId, TerminalPalette } from "@blit-sh/core";
import { useBlitContext, useRequiredBlitWorkspace } from "./BlitContext";
import { createBlitWorkspaceState } from "./hooks/createBlitWorkspace";

export interface BlitTerminalProps {
  sessionId: SessionId | null;
  fontFamily?: string;
  fontSize?: number;
  class?: string;
  style?: JSX.CSSProperties;
  palette?: TerminalPalette;
  readOnly?: boolean;
  showCursor?: boolean;
  onRender?: (renderMs: number) => void;
  scrollbarColor?: string;
  scrollbarWidth?: number;
  advanceRatio?: number;
}

/**
 * BlitTerminal renders a blit terminal inside a WebGL canvas.
 *
 * This is a thin Solid wrapper over `BlitTerminalSurface` from `@blit-sh/core`.
 * It renders a container `<div>`, attaches the surface on mount, and uses
 * `createEffect` to forward reactive prop changes to the surface.
 */
export function BlitTerminal(props: BlitTerminalProps) {
  const ctx = useBlitContext();
  const workspace = useRequiredBlitWorkspace();
  const snapshot = createBlitWorkspaceState(workspace);

  let containerRef!: HTMLDivElement;
  let surface: BlitTerminalSurface | null = null;

  onMount(() => {
    surface = new BlitTerminalSurface({
      sessionId: props.sessionId,
      fontFamily: props.fontFamily ?? ctx.fontFamily,
      fontSize: props.fontSize ?? ctx.fontSize,
      palette: props.palette ?? ctx.palette,
      readOnly: props.readOnly,
      showCursor: props.showCursor,
      onRender: props.onRender,
      scrollbarColor: props.scrollbarColor,
      scrollbarWidth: props.scrollbarWidth,
      advanceRatio: props.advanceRatio ?? ctx.advanceRatio,
    });

    surface.setWorkspace(workspace);
    surface.attach(containerRef);
  });

  onCleanup(() => {
    surface?.dispose();
    surface = null;
  });

  // Forward connection changes. Reading snapshot() inside createEffect makes
  // this reactive — it re-runs whenever the workspace snapshot changes
  // (connection status transitions, new sessions, etc.).
  createEffect(() => {
    const snap = snapshot();
    const session = props.sessionId
      ? (snap.sessions.find((s) => s.id === props.sessionId) ?? null)
      : null;
    const conn = session ? workspace.getConnection(session.connectionId) : null;
    surface?.setConnection(conn);
  });

  // Forward prop changes.
  createEffect(() => surface?.setSessionId(props.sessionId));
  createEffect(() => surface?.setPalette(props.palette ?? ctx.palette));
  createEffect(() =>
    surface?.setFontFamily(props.fontFamily ?? ctx.fontFamily),
  );
  createEffect(() => surface?.setFontSize(props.fontSize ?? ctx.fontSize));
  createEffect(() => surface?.setShowCursor(props.showCursor));
  createEffect(() => surface?.setOnRender(props.onRender));
  createEffect(() =>
    surface?.setAdvanceRatio(props.advanceRatio ?? ctx.advanceRatio),
  );
  createEffect(() => surface?.setReadOnly(props.readOnly));

  // Re-send dimensions when connection becomes ready.
  createEffect(() => {
    const snap = snapshot();
    const session = props.sessionId
      ? (snap.sessions.find((s) => s.id === props.sessionId) ?? null)
      : null;
    const connection = session
      ? (snap.connections.find((c) => c.id === session.connectionId) ?? null)
      : null;
    if (
      connection?.status === "connected" &&
      props.sessionId !== null &&
      !props.readOnly
    ) {
      surface?.resendSize();
    }
  });

  return (
    <div
      ref={containerRef}
      class={props.class}
      style={{
        position: "relative",
        overflow: "hidden",
        ...props.style,
      }}
    />
  );
}
