// js/react/src/BlitContext.tsx
import { createContext, useContext, useMemo, type ReactNode } from "react";
import type { TerminalPalette } from "@blit-sh/core";
import type { BlitWorkspace } from "@blit-sh/core";

export interface BlitContextValue {
  workspace?: BlitWorkspace;
  palette?: TerminalPalette;
  fontFamily?: string;
  fontSize?: number;
  advanceRatio?: number;
  textGamma?: number;
}

const BlitContext = createContext<BlitContextValue>({});

export function useBlitContext(): BlitContextValue {
  return useContext(BlitContext);
}

export interface BlitProviderProps extends BlitContextValue {
  children: ReactNode;
}

export function BlitWorkspaceProvider({
  children,
  workspace,
  palette,
  fontFamily,
  fontSize,
  advanceRatio,
  textGamma,
}: BlitProviderProps) {
  const value = useMemo(
    () => ({
      workspace,
      palette,
      fontFamily,
      fontSize,
      advanceRatio,
      textGamma,
    }),
    [workspace, palette, fontFamily, fontSize, advanceRatio, textGamma],
  );
  return <BlitContext.Provider value={value}>{children}</BlitContext.Provider>;
}

export function useRequiredBlitWorkspace(): BlitWorkspace {
  const workspace = useBlitContext().workspace;
  if (!workspace) {
    throw new Error("Blit components require a BlitWorkspaceProvider ancestor");
  }
  return workspace;
}

// js/solid/src/BlitContext.tsx
import { createContext, useContext, type JSX } from "solid-js";
import type { BlitWorkspace, TerminalPalette } from "@blit-sh/core";

export interface BlitContextValue {
  workspace?: BlitWorkspace;
  palette?: TerminalPalette;
  fontFamily?: string;
  fontSize?: number;
  advanceRatio?: number;
  textGamma?: number;
}

const BlitContext = createContext<BlitContextValue>({});

export function useBlitContext(): BlitContextValue {
  return useContext(BlitContext);
}

export interface BlitProviderProps extends BlitContextValue {
  children: JSX.Element;
}

export function BlitWorkspaceProvider(props: BlitProviderProps) {
  return (
    <BlitContext.Provider
      value={{
        get workspace() {
          return props.workspace;
        },
        get palette() {
          return props.palette;
        },
        get fontFamily() {
          return props.fontFamily;
        },
        get fontSize() {
          return props.fontSize;
        },
        get advanceRatio() {
          return props.advanceRatio;
        },
        get textGamma() {
          return props.textGamma;
        },
      }}
    >
      {props.children}
    </BlitContext.Provider>
  );
}

export function useRequiredBlitWorkspace(): BlitWorkspace {
  const ctx = useBlitContext();
  if (!ctx.workspace) {
    throw new Error("Blit components require a BlitWorkspaceProvider ancestor");
  }
  return ctx.workspace;
}
